name: Deploy Node.js Backend
on:
  push:
    branches:
      - main  # Triggers on push to main branch

jobs:
  backend-deploy:
    name: Deploy API to Hostinger
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # - name: Create Restart Trigger
    #   run: |
    #     mkdir -p tmp
    #     touch tmp/restart.txt

    - name: Sync files to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        local-dir: ./
        server-dir: /nodejs/
        exclude: |
          **/node_modules/**
          **/.git/**
          **/.github/**
          **/tests/**
          .env
          .eslintrc.js
          .prettierrc
          jest.config.js
          README.md